### ISSUE TITLE
Style improvement

### ISSUE THREAD

**Issue by rollecode** [yefengr/obsidian-daily-statistics#7]
Hello! Didn't make a PR because I'm in a rush, but this is in my custom.css:

```css
/* Daily Statistics plugin tweaks */
.el-calendar button:focus,
.el-calendar button:hover,
.el-calendar button {
  background: none;
  border: 0;
  box-shadow: none;
  line-height: .7;
  padding: 0;
}

/* stylelint-disable-next-line */
.el-calendar-day > .div-container > .flex-centered3,
.el-button-group::after,
.el-button-group::before {
  display: none;
}

.el-calendar .el-button-group {
  display: inline-flex;
  flex-wrap: wrap;
  gap: 0 15px;
}

.el-calendar-table .el-calendar-day {
  height: 50px;
}

.el-calendar-day > .div-container > .flex-centered {
  font-weight: 600;
}

.el-calendar__header {
  display: block;
}

/* stylelint-disable-next-line */
.el-calendar__title {
  font-size: 14px;
  margin-bottom: 5px;
}

/* stylelint-disable-next-line */
.el-calendar-day > .div-container p {
  font-size: 12px;
}

.el-calendar-day > .div-container {
  gap: 5px;
}
```

## Before

![image](https://github.com/user-attachments/assets/17f08c4f-8c40-4383-9af5-f3640f562c75)

## After

![image](https://github.com/user-attachments/assets/19d0f704-470e-4038-a07e-e7e2879021a4)

You can decide if you want to use it or close this issue. :sweat_smile:
